In [142]:
import pandas as pd
import numpy as np

In [143]:
df = pd.read_csv('collected research people.csv')

df.head()

,Unnamed: 0,Nome,Endereerço,Cidade,Estado,phone,anual_income,Estado Civil,AAge,n_filhos,Moradia,Food_restrictions,streaming,diariamente_sun blocker,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,email
0,0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 37 entries, 0 to 36
Data columns (total 20 columns):
 #   Column                            Non-Null Count  Dtype
---  ------                            --------------  -----
 0   Unnamed: 0                        37 non-null     int64
 1   Nome                              37 non-null     object
 2   Endereerço                        29 non-null     object
 3   Cidade                            27 non-null     object
 4   Estado                            24 non-null     object
 5   phone                             25 non-null     object
 6   anual_income                      25 non-null     float64
 7   Estado Civil                      25 non-null     object
 8   AAge                              30 non-null     float64
 9   n_filhos                          22 non-null     float64
 10  Moradia                           28 non-null     object
 11  Food_restrictions                 24 non-null     object
 12  streaming                         22 non-null     object
 13  diariamente_sun blocker           25 non-null     object
 14  Vai na Praia Mensalmente          29 non-null     object
 15  Faz Academia                      21 non-null     object
 16  Compra e Lê Livros Todos os Anos  23 non-null     object
 17  Quantidade de Livros Comprados    10 non-null     float64
 18  Autor Favorito                    12 non-null     object
 19  email                             37 non-null     object
dtypes: float64(4), int64(1), object(15)
memory usage: 5.9+ KB

In [145]:
## Arrumando os dados
new_columns = {
    "Endereerço": "Endereço",
    "phone": "Telefone",
    "anual_income": "Renda Anual",
    "AAge": "Idade",
    "n_filhos": "Número de Filhos",
    "Food_restrictions": "Restrições Alimentares",
    "streaming": "Streaming",
    "diariamente_sun blocker": "Usa protetor solar diariamente",
    "email": "Email",
}

df.rename(columns=new_columns, inplace=True)
df.drop(columns=["Unnamed: 0"], inplace=True)

In [146]:
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira>,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr. Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo%,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

### Arrumando os dados das colunas

In [147]:
## Coluna de nome:
df.Nome = df.Nome.str.replace('[^a-zA-Zà-úÀ-Ú ]', '', regex=True)
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,S,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [148]:
df['Estado Civil'].value_counts()

Estado Civil
Divorciado    6
Solteiro      5
Casado        3
D             3
Viúvo         3
S             2
V             2
C             1
Name: count, dtype: int64

In [149]:
## Coluna de Estado civil:
df['Estado Civil'] = df['Estado Civil'].replace({
                                        'S': 'Solteiro', 
                                        'D': 'Divorciado', 
                                        'C': 'Casado', 
                                        'V': 'Viúvo'})
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0.'8--%/],53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [150]:
df['Estado Civil'].value_counts()

Estado Civil
Divorciado    9
Solteiro      7
Viúvo         5
Casado        4
Name: count, dtype: int64

In [151]:
df['Telefone'].value_counts()

Telefone
(011) 3908 5991        1
;~).,-:5~=             1
(061) 5002 3548        1
+55 51 8245 2336       1
8:<$9@\:~/             1
+55 51 2213 5603       1
21 0712-6859           1
+55 71 7088-8329       1
84 6014-5325           1
(011) 3410 5199        1
(084) 0305 6725        1
+55 (021) 4719 9862    1
51 5882 5998           1
-0.'8--%/]             1
0800 612 6032          1
84 2319-1532           1
41 5504 8546           1
^{{52$,,78             1
81 2891-7504           1
0900 093 9760          1
+55 51 6868 3666       1
5}|#:}~<7~             1
84 9687 5023           1
+55 (084) 4591-2403    1
'|2{938(=[             1
Name: count, dtype: int64

In [152]:
df['Telefone'] = df['Telefone'].str.replace('[^0-9() +-]', '*', regex=True)
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,-0**8--***,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [153]:
df['Telefone'] = df['Telefone'].mask(df['Telefone'].str.contains(r'\*', na=False), np.nan)
df.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [154]:
df.Telefone.value_counts()

Telefone
(011) 3908 5991        1
+55 (021) 4719 9862    1
+55 51 8245 2336       1
+55 51 2213 5603       1
21 0712-6859           1
+55 71 7088-8329       1
84 6014-5325           1
(011) 3410 5199        1
(084) 0305 6725        1
51 5882 5998           1
+55 (084) 4591-2403    1
0800 612 6032          1
84 2319-1532           1
41 5504 8546           1
81 2891-7504           1
0900 093 9760          1
+55 51 6868 3666       1
84 9687 5023           1
(061) 5002 3548        1
Name: count, dtype: int64

### Cenário 1

In [155]:
## Vamos ver quem pode fazer parte do minha casa minha vida, vendo se possui reenda anula maior que 104 e tmb se tem a casa quitada, de favor etc.
df_cenario_1 = df.copy()
df_cenario_1.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [157]:
df_cenario_1['Minha casa minha vida'] = np.where(df_cenario_1['Renda Anual'] > 104, 'Pode', 'Nao pode')
df_cenario_1.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email,Minha casa minha vida
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com,Pode
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com,Pode
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com,Nao pode
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com,Pode
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com,Pode

#### Para quem é bom investir

Seria bom investir quem ja possui casa propria, ou quitada.

In [160]:
df_cenario_1['Investimento'] = np.where((df_cenario_1['Moradia']=='Quitada') | (df_cenario_1['Moradia']=='Financiamento'), 'Pode', 'Não investir')
df_cenario_1.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,...,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email,Minha casa minha vida,Investimento
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,...,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com,Pode,Pode
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,...,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com,Pode,Não investir
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,...,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com,Nao pode,Pode
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,...,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com,Pode,Pode
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,...,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com,Pode,Pode

## Cenário 2

In [161]:
df_cenario_2 = df.copy()
df_cenario_2.head()

,Nome,Endereço,Cidade,Estado,Telefone,Renda Anual,Estado Civil,Idade,Número de Filhos,Moradia,Restrições Alimentares,Streaming,Usa protetor solar diariamente,Vai na Praia Mensalmente,Faz Academia,Compra e Lê Livros Todos os Anos,Quantidade de Livros Comprados,Autor Favorito,Email
0,Maria Clara Novaes,NaN,Carvalho,Mato Grosso do Sul,(011) 3908 5991,86445.0,NaN,43.0,NaN,Quitada,Nenhuma,Globo Play,Sim,Não,Sim,NaN,NaN,NaN,mariaclaranovaes285@gemeil.com
1,Davi Lucca Pereira,"Rodovia de Silveira, 67",NaN,Mato Grosso do Sul,NaN,31289.0,NaN,NaN,0.0,De favor,NaN,Todos,NaN,Não,Sim,Não,NaN,NaN,daviluccapereira933@exemplo.com
2,Sr Caio Caldeira,"Residencial Freitas, 10",Carvalho,Rio Grande do Norte,NaN,NaN,Solteiro,60.0,NaN,Financiamento,Lactose e Glúten,NaN,Sim,Não,NaN,Sim,6.0,NaN,srcaiocaldeira626@gemeil.com
3,Kaique Azevedo,NaN,Azevedo,Rio Grande do Sul,NaN,76264.0,Casado,26.0,4.0,Quitada,Lactose e Glúten,NaN,Não,Não,Não,Sim,0.0,Enzo Rezende,kaiqueazevedo731@rotmail.com
4,Pedro Moreira,"Colônia de Oliveira, 87",NaN,NaN,NaN,53295.0,Casado,60.0,5.0,Financiamento,NaN,Globo Play,Sim,Sim,NaN,Sim,7.0,NaN,pedromoreira622@gemeil.com

In [166]:
## Para saber sobre o cenário 2, vamos ver quem Streaming e quais os streamings
df_cenario_2.Streaming.replace({'Netflix e Disney': 'Netflix e Disney Plus'},inplace=True)
df_cenario_2.Streaming.replace({'Todos': 'Globo Play e Netflix e HBO e Disney Plus e Crunchyroll'},inplace=True)

research_hillo_stream = df_cenario_2['Streaming'].str.get_dummies(sep=' e ')
research_hillo_stream.head()

   Crunchyroll  Disney Plus  Globo Play  HBO  Nenhum  Netflix
0            0            0           1    0       0        0
1            1            1           1    1       0        1
2            0            0           0    0       0        0
3            0            0           0    0       0        0
4            0            0           1    0       0        0

In [170]:
contagem = research_hillo_stream.sum()
contagem = contagem.sort_values(ascending=False)
print(contagem)

Globo Play     8
HBO            7
Disney Plus    6
Netflix        6
Crunchyroll    5
Nenhum         4
dtype: int64

Podemos ver que oque mais compensa a empresa Hillo a fazer o investimento seria na Globo Play